apiVersion: v1
kind: Service
metadata:
  name: "{{ include "nostradamus.fullname" . }}-ui"
  labels:
    {{- include "nostradamus.labels" . | nindent 4 }}
    nostradamus-platform: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.ui.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "nostradamus.selectorLabels" . | nindent 4 }}
    nostradamus-platform: ui
